jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print repo name  # Challenge 5
      run:  echo "Repository: ${{ github.repository }}"

    - name: Print current date  # Challenge 1
      run: date

    - name: Run hello.sh  # Challenge 2
      run: bash hello.sh

    - name: Linux-only step  # Challenge 3
      if: runner.os == 'Linux'
      run: echo "Running this step only on Linux."

    - name: Echo API key  # Challenge 4
      run: echo "Secret API Key is ${{ secrets.API_KEY }}"
