name: CI Workflow

on:
  push:
    branches: [main]                # 🔹 Challenge 1: Run on push to main
  schedule:                         # 🔹 Challenge 8: Nightly CRON build
    - cron: '0 1 * * *'
  workflow_dispatch:               # 🔹 Challenge 10: Manual trigger with input
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:                      # 🔹 Challenge 9: Matrix for Python versions
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: 🔹 Checkout code        # 🔹 Challenge 5
      uses: actions/checkout@v3

    - name:  Print repo name      #  Challenge 5
      run: echo "Repository: ${{ github.repository }}"

    - name: 🔹 Print current date   # 🔹 Challenge 1
      run: date

    - name: 🔹 Run hello.sh         # 🔹 Challenge 2
      run: bash hello.sh

    - name: 🔹 Linux-only step      # 🔹 Challenge 3
      if: runner.os == 'Linux'
      run: echo "Running this step only on Linux."

    - name: 🔹 Echo API key         # 🔹 Challenge 4
      run: echo "Secret API Key is ${{ secrets.API_KEY }}"

    - name: 🔹 Set up Python        # 🔹 Challenge 6
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 🔹 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install pytest

    - name: 🔹 Run tests (pytest)
      run: |
        pytest > test-report.txt

    - name: 🔹 Upload test report   # 🔹 Challenge 7
      uses: actions/upload-artifact@v4
      with:
        name: test-report-${{ matrix.python-version }}
        path: test-report.txt

    - name: 🔹 Notify on success    # 🔹 Challenge 11
      if: success()
      run: echo "✅ Tests passed for ${{ github.repository }} on branch ${{ github.ref }}"

    - name: 🔹 Send Slack Notification (optional)
      if: always()  # Run regardless of success or failure
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        if [ -n "$SLACK_WEBHOOK" ]; then
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"📢 CI Workflow completed for '"${{ github.repository }}"' on '"${{ github.ref }}"'"}' \
          $SLACK_WEBHOOK
        fi
